# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 SteamZero contributors
"""Contratos operacionais publicados para a central handheld.

Este módulo é a fonte de verdade da ligação backend → tela → controle. A QML
recebe este catálogo pelo ``/status`` e usa ``id`` para resolver método,
endpoint, confirmação, schema de entrada, semântica de job e rollback. Rotas
deliberadamente ausentes da GUI também aparecem, com justificativa explícita.
"""

from __future__ import annotations

from typing import Any

_STATES = ("ready", "empty", "degraded", "pending", "failed", "offline")


def _schema(*required: str, **properties: str) -> dict[str, Any]:
    return {
        "type": "object",
        "required": list(required),
        "properties": {name: {"type": kind} for name, kind in properties.items()},
        "additionalProperties": False,
    }


def _action(
    action_id: str,
    label: str,
    endpoint: str | None,
    *,
    service: str,
    screen: str,
    control: str,
    method: str = "POST",
    schema: dict[str, Any] | None = None,
    confirmation: str = "none",
    job: str = "synchronous",
    poll_endpoint: str | None = None,
    rollback_endpoint: str | None = None,
    enabled: bool = True,
    reason: str = "",
    applicable: bool = True,
    states: tuple[str, ...] = _STATES,
) -> dict[str, Any]:
    return {
        "id": action_id,
        "label": label,
        "enabled": enabled,
        "reason": reason,
        "service": service,
        "endpoint": endpoint,
        "method": method if endpoint else None,
        "screen": screen,
        "control": control,
        "states": list(states),
        "applicability": "applicable" if applicable else "not-applicable",
        "confirmation": {"required": confirmation != "none", "mode": confirmation},
        "inputSchema": schema or _schema(),
        "jobSemantics": {
            "kind": job,
            "states": (
                ["queued", "running", "succeeded", "failed", "cancelled"]
                if job == "asynchronous"
                else ["succeeded", "failed"]
            ),
            "pollEndpoint": poll_endpoint,
        },
        "rollback": {
            "supported": rollback_endpoint is not None,
            "endpoint": rollback_endpoint,
        },
    }


def handheld_ui_contracts() -> dict[str, Any]:
    """Retorna a matriz verificável consumida pela QML e pelos testes."""
    actions = [
        _action(
            "desktop.status",
            "Atualizar central",
            "/status",
            service="bridge",
            screen="global",
            control="refresh",
            method="GET",
        ),
        _action(
            "desktop.profile.plan",
            "Revisar perfil",
            "/plan",
            service="controller",
            screen="profiles",
            control="profile-plan",
            schema=_schema("profile", profile="string"),
        ),
        _action(
            "desktop.profile.apply",
            "Aplicar perfil",
            "/apply",
            service="controller",
            screen="profiles",
            control="profile-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/recover",
        ),
        _action(
            "desktop.profile.reset",
            "Aplicar modo seguro",
            "/reset",
            service="controller",
            screen="profiles",
            control="safe-reset",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/recover",
        ),
        _action(
            "desktop.recover",
            "Recuperar Desktop",
            "/recover",
            service="controller",
            screen="system",
            control="desktop-recover",
            confirmation="dialog",
        ),
        _action(
            "desktop.conflict.plan",
            "Revisar conflito",
            "/conflict/plan",
            service="controller",
            screen="overview",
            control="conflict-plan",
            schema=_schema("actionId", actionId="string"),
        ),
        _action(
            "desktop.conflict.apply",
            "Resolver conflito",
            "/conflict/apply",
            service="controller",
            screen="overview",
            control="conflict-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "component.plan",
            "Revisar instalação",
            "/component/plan",
            service="components",
            screen="emulators",
            control="component-menu",
            schema=_schema("componentId", componentId="string"),
        ),
        _action(
            "component.apply",
            "Aplicar componente",
            "/component/apply",
            service="components",
            screen="emulators",
            control="component-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "component.launch",
            "Abrir componente",
            "/component/launch",
            service="components",
            screen="emulators",
            control="component-menu",
            schema=_schema("componentId", componentId="string"),
        ),
        _action(
            "component.rollback",
            "Desfazer componente",
            None,
            service="components",
            screen="system",
            control="component-history",
            enabled=False,
            reason=(
                "O engine possui rollback interno, mas a bridge Desktop não expõe "
                "seleção auditável de operação por componente."
            ),
            applicable=False,
        ),
        _action(
            "component.recover",
            "Recuperar componente",
            None,
            service="components",
            screen="system",
            control="component-recovery",
            enabled=False,
            reason=(
                "A recuperação automática ocorre no engine; não há endpoint Desktop "
                "para uma recuperação manual isolada."
            ),
            applicable=False,
        ),
        _action(
            "emulator.plan",
            "Revisar emulador",
            "/emulation/emulator/plan",
            service="emulation",
            screen="emulators",
            control="emulator-menu",
            schema=_schema("emulatorId", "action", emulatorId="string", action="string"),
        ),
        _action(
            "emulator.apply",
            "Aplicar no emulador",
            "/emulation/emulator/apply",
            service="emulation",
            screen="emulators",
            control="emulator-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "emulator.launch",
            "Abrir emulador",
            "/emulation/emulator/launch",
            service="emulation",
            screen="emulators",
            control="emulator-menu",
            schema=_schema("emulatorId", emulatorId="string"),
        ),
        _action(
            "emulator.stop",
            "Parar emulador",
            "/emulation/emulator/stop",
            service="emulation",
            screen="emulators",
            control="emulator-menu",
            schema=_schema("emulatorId", emulatorId="string"),
            confirmation="dialog",
        ),
        _action(
            "game.launch",
            "Jogar",
            "/emulation/game/launch",
            service="library",
            screen="library",
            control="game-primary",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "playtime.continue.emulation",
            "Continuar jogo emulado",
            "/emulation/game/launch",
            service="playtime",
            screen="overview",
            control="continue-playing",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "cloud.launch",
            "Abrir serviço cloud",
            "/cloud/launch",
            service="emulation",
            screen="emulation",
            control="cloud-primary",
            schema=_schema("platformId", platformId="string"),
        ),
        _action(
            "emulation.action.plan",
            "Revisar alteração",
            "/emulation/action/plan",
            service="emulation",
            screen="emulation",
            control="action-plan",
            schema={
                "type": "object",
                "required": ["actionId"],
                "properties": {"actionId": {"type": "string"}},
                "additionalProperties": True,
            },
        ),
        _action(
            "emulation.action.apply",
            "Confirmar alteração",
            "/emulation/action/apply",
            service="emulation",
            screen="emulation",
            control="action-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/emulation/action/rollback",
        ),
        _action(
            "emulation.action.rollback",
            "Desfazer alteração",
            "/emulation/action/rollback",
            service="emulation",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "library.scan",
            "Escanear biblioteca",
            "/emulation/library/scan",
            service="library",
            screen="library",
            control="scan",
            job="asynchronous",
            poll_endpoint="/emulation/job/status/{jobId}",
        ),
        _action(
            "job.status",
            "Ver tarefa",
            "/emulation/job/status",
            service="jobs",
            screen="tasks",
            control="task-row",
            schema=_schema("jobId", jobId="string"),
        ),
        _action(
            "jobs.list",
            "Listar tarefas",
            "/emulation/jobs",
            service="jobs",
            screen="tasks",
            control="task-center",
            method="GET",
        ),
        _action(
            "job.cancel",
            "Cancelar tarefa",
            "/emulation/job/cancel",
            service="jobs",
            screen="tasks",
            control="task-row-cancel",
            schema=_schema("jobId", jobId="string"),
            confirmation="dialog",
        ),
        _action(
            "job.retry",
            "Tentar novamente",
            "/emulation/job/retry",
            service="jobs",
            screen="tasks",
            control="task-row-retry",
            schema=_schema("jobId", jobId="string"),
        ),
        _action(
            "steam.open",
            "Abrir Steam",
            "/steam/open",
            service="steam",
            screen="steam",
            control="steam-action",
            schema=_schema("target", target="string"),
        ),
        _action(
            "playtime.continue.steam",
            "Continuar jogo Steam",
            "/steam/game/launch",
            service="playtime",
            screen="overview",
            control="continue-playing",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "playtime.recover.steam",
            "Recuperar sessão Steam",
            "/steam/gameplay/recover",
            service="playtime",
            screen="overview",
            control="continue-playing",
            schema=_schema("gameId", gameId="string"),
            confirmation="dialog",
        ),
        _action(
            "collections.list",
            "Ver coleções",
            "/collections",
            service="library",
            screen="overview",
            control="collection-summary",
            method="GET",
        ),
        _action(
            "collections.plan",
            "Revisar alteração de coleção",
            "/collections/plan",
            service="library",
            screen="overview",
            control="collection-edit",
            schema=_schema("action", action="object"),
            confirmation="dialog",
        ),
        _action(
            "collections.apply",
            "Aplicar alteração de coleção",
            "/collections/apply",
            service="library",
            screen="overview",
            control="collection-edit",
            schema=_schema(
                "planId",
                "confirmToken",
                planId="string",
                confirmToken="string",
            ),
            confirmation="dialog",
        ),
        _action(
            "library.health",
            "Ver saúde da coleção",
            "/library/health",
            service="library",
            screen="overview",
            control="library-health",
            method="GET",
        ),
        _action(
            "library.health.plan",
            "Revisar verificação anti-bitrot",
            "/library/health/plan",
            service="library",
            screen="overview",
            control="library-health-scan",
            schema=_schema(),
            confirmation="dialog",
        ),
        _action(
            "library.health.apply",
            "Executar verificação anti-bitrot",
            "/library/health/apply",
            service="library",
            screen="overview",
            control="library-health-scan",
            schema=_schema(
                "planId",
                "confirmToken",
                planId="string",
                confirmToken="string",
            ),
            confirmation="dialog",
        ),
        _action(
            "steam.input.open",
            "Configurar Steam Input",
            "/steam/input/open",
            service="steam",
            screen="steam",
            control="steam-input",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "hud.presets",
            "Consultar presets HUD",
            "/hud/presets",
            service="steam",
            screen="steam-gameplay",
            control="mangohud-presets",
            method="GET",
        ),
        _action(
            "steam.gameplay.plan",
            "Revisar perfil Steam",
            "/steam/gameplay/plan",
            service="steam",
            screen="steam",
            control="gameplay-plan",
            schema={
                "type": "object",
                "required": ["gameId"],
                "properties": {"gameId": {"type": "string"}},
                "additionalProperties": True,
            },
        ),
        _action(
            "steam.gameplay.apply",
            "Aplicar perfil Steam",
            "/steam/gameplay/apply",
            service="steam",
            screen="steam",
            control="gameplay-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/steam/gameplay/rollback",
        ),
        _action(
            "steam.gameplay.rollback",
            "Desfazer perfil Steam",
            "/steam/gameplay/rollback",
            service="steam",
            screen="steam",
            control="gameplay-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "steam.gameplay.recover",
            "Recuperar perfil Steam",
            "/steam/gameplay/recover",
            service="steam",
            screen="steam",
            control="gameplay-recover",
            schema=_schema("gameId", gameId="string"),
            confirmation="dialog",
        ),
        _action(
            "steam.launch-options.plan",
            "Revisar opções de lançamento",
            "/steam/gameplay/launch-options/plan",
            service="steam",
            screen="steam",
            control="launch-options-plan",
            schema=_schema("gameId", gameId="string"),
        ),
        _action(
            "steam.launch-options.apply",
            "Aplicar opções de lançamento",
            "/steam/gameplay/launch-options/apply",
            service="steam",
            screen="steam",
            control="launch-options-apply",
            schema=_schema(
                "planId",
                "confirmToken",
                "gameId",
                planId="string",
                confirmToken="string",
                gameId="string",
            ),
            confirmation="token",
            rollback_endpoint="/steam/gameplay/launch-options/rollback",
        ),
        _action(
            "steam.launch-options.rollback",
            "Desfazer opções de lançamento",
            "/steam/gameplay/launch-options/rollback",
            service="steam",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "steam.maintenance.plan",
            "Revisar manutenção",
            "/steam/maintenance/plan",
            service="maintenance",
            screen="steam",
            control="maintenance-plan",
            schema=_schema("gameId", "categories", gameId="string", categories="array"),
        ),
        _action(
            "steam.maintenance.apply",
            "Executar manutenção",
            "/steam/maintenance/apply",
            service="maintenance",
            screen="steam",
            control="maintenance-apply",
            schema=_schema(
                "planId",
                "confirmToken",
                "confirmPhrase",
                planId="string",
                confirmToken="string",
                confirmPhrase="string",
            ),
            confirmation="phrase",
            rollback_endpoint="/steam/maintenance/recover",
        ),
        _action(
            "steam.maintenance.recover",
            "Recuperar manutenção",
            "/steam/maintenance/recover",
            service="maintenance",
            screen="system",
            control="maintenance-recover",
            confirmation="dialog",
        ),
        _action(
            "steam.media.plan",
            "Revisar publicação Steam",
            "/steam/media/plan",
            service="media",
            screen="media",
            control="steam-media-plan",
            schema=_schema(
                "gameId",
                "accountId",
                "packagePath",
                gameId="string",
                accountId="string",
                packagePath="string",
            ),
        ),
        _action(
            "steam.media.apply",
            "Publicar mídia na Steam",
            "/steam/media/apply",
            service="media",
            screen="media",
            control="steam-media-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            job="asynchronous",
            rollback_endpoint="/steam/media/rollback",
        ),
        _action(
            "steam.media.rollback",
            "Desfazer publicação Steam",
            "/steam/media/rollback",
            service="media",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "lsfg.plan",
            "Revisar LSFG",
            "/system/lsfg/plan",
            service="components",
            screen="system",
            control="lsfg-plan",
        ),
        _action(
            "lsfg.apply",
            "Instalar LSFG",
            "/system/lsfg/apply",
            service="components",
            screen="system",
            control="lsfg-apply",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="token",
            rollback_endpoint="/system/lsfg/rollback",
        ),
        _action(
            "lsfg.rollback",
            "Desfazer LSFG",
            "/system/lsfg/rollback",
            service="components",
            screen="system",
            control="operation-rollback",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "keyboard.toggle",
            "Alternar teclado",
            "/keyboard",
            service="session",
            screen="global",
            control="keyboard",
            schema=_schema(action="string", language="string"),
        ),
        _action(
            "keyboard.settings",
            "Salvar conforto do teclado",
            "/keyboard/settings",
            service="session",
            screen="system",
            control="keyboard-settings",
            schema={
                "type": "object",
                "properties": {
                    "sound": {"type": "boolean"},
                    "haptic": {"type": "boolean"},
                    "theme": {"type": "string"},
                },
                "additionalProperties": False,
            },
        ),
        _action(
            "session.select",
            "Trocar sessão",
            "/session/select",
            service="session",
            screen="overview",
            control="session-switch",
            schema={
                "type": "object",
                "required": ["target"],
                "properties": {
                    "target": {"type": "string"},
                    "planId": {"type": "string"},
                    "confirmToken": {"type": "string"},
                },
                "additionalProperties": False,
            },
            confirmation="two-step",
        ),
        _action(
            "terminal.open",
            "Abrir terminal",
            "/ashyterm",
            service="session",
            screen="system",
            control="terminal",
        ),
        _action(
            "panel.autohide",
            "Alternar painel",
            "/panel/autohide",
            service="controller",
            screen="profiles",
            control="panel-toggle",
            schema=_schema("enable", enable="boolean"),
        ),
        _action(
            "credential.status",
            "Atualizar credenciais",
            "/scraping/credential/status",
            service="media",
            screen="media",
            control="credential-refresh",
        ),
        _action(
            "credential.save",
            "Salvar credencial",
            "/scraping/credential/save",
            service="media",
            screen="media",
            control="credential-save",
            schema=_schema("provider", "credentials", provider="string", credentials="object"),
            confirmation="dialog",
        ),
        _action(
            "credential.test",
            "Testar credencial",
            "/scraping/credential/test",
            service="media",
            screen="media",
            control="credential-test",
            schema=_schema("provider", provider="string"),
        ),
        _action(
            "credential.delete",
            "Remover credencial",
            "/scraping/credential/delete",
            service="media",
            screen="media",
            control="credential-delete",
            schema=_schema("provider", provider="string"),
            confirmation="dialog",
        ),
        _action(
            "provider.link",
            "Abrir documentação do provider",
            "/scraping/provider-link",
            service="media",
            screen="media",
            control="provider-link",
            schema=_schema("provider", "link", provider="string", link="string"),
        ),
        _action(
            "sync.status",
            "Ver fila de sincronização",
            None,
            service="sync",
            screen="sync",
            control="sync-summary",
            method="GET",
            enabled=False,
            reason=(
                "A fila é somente leitura no snapshot atual; retry/cancel ainda não "
                "possuem rota da bridge."
            ),
            applicable=False,
        ),
        _action(
            "profiles.history",
            "Ver histórico de perfis",
            None,
            service="steam",
            screen="steam",
            control="profile-history",
            method="GET",
            enabled=False,
            reason=(
                "A UI revisa diferenças antes de aplicar e oferece recovery, mas o store "
                "não publica uma linha do tempo de perfis pela bridge."
            ),
            applicable=False,
        ),
        _action(
            "operations.history",
            "Ver histórico de operações",
            "/system/operations",
            service="system",
            screen="system",
            control="operation-history",
            method="GET",
            schema=_schema(),
        ),
        _action(
            "operations.detail",
            "Ver detalhes da operação",
            "/system/operations/show",
            service="system",
            screen="system",
            control="operation-detail",
            method="POST",
            schema=_schema("operationId", operationId="string"),
        ),
        _action(
            "operations.rollback.plan",
            "Revisar rollback da operação",
            "/system/operations/rollback/plan",
            service="system",
            screen="system",
            control="operation-rollback",
            method="POST",
            schema=_schema("operationId", operationId="string"),
            confirmation="dialog",
        ),
        _action(
            "operations.rollback.apply",
            "Confirmar rollback da operação",
            "/system/operations/rollback/apply",
            service="system",
            screen="system",
            control="operation-rollback",
            method="POST",
            schema=_schema(
                "planId",
                "confirmToken",
                planId="string",
                confirmToken="string",
            ),
            confirmation="dialog",
        ),
        _action(
            "state.export",
            "Exportar estado",
            "/system/diagnostics/export/plan",
            service="system",
            screen="system",
            control="diagnostics-export",
            schema=_schema("destination", "kind", destination="string", kind="string"),
            confirmation="dialog",
        ),
        _action(
            "admin.health",
            "Ver saúde administrativa",
            "/system/admin/health",
            service="system",
            screen="system",
            control="admin-health",
            method="GET",
            schema=_schema(),
        ),
        _action(
            "session.recovery",
            "Recuperar sessão de jogo",
            None,
            service="session",
            screen="system",
            control="session-recovery",
            enabled=False,
            reason=(
                "A recuperação de sessão pertence ao daemon e ainda não possui contrato Desktop."
            ),
            applicable=False,
        ),
        _action(
            "support.bundle",
            "Exportar pacote de suporte",
            "/system/diagnostics/export/plan",
            service="system",
            screen="system",
            control="support-bundle",
            schema=_schema("destination", "kind", destination="string", kind="string"),
            confirmation="dialog",
        ),
        _action(
            "diagnostics.export.apply",
            "Confirmar exportação revisada",
            "/system/diagnostics/export/apply",
            service="system",
            screen="system",
            control="diagnostics-export-confirm",
            schema=_schema("planId", "confirmToken", planId="string", confirmToken="string"),
            confirmation="dialog",
        ),
        # --- Compartilhamento de tela (ADR-0022) ---------------------------
        _action(
            "cast.discover",
            "Descobrir receptores",
            "/cast/discover",
            service="bridge",
            screen="cast",
            control="cast-discover",
            method="GET",
        ),
        _action(
            "cast.pair",
            "Parear receptor",
            "/cast/pair",
            service="bridge",
            screen="cast",
            control="cast-pair",
            schema=_schema("receiverId", receiverId="string", pin="string"),
        ),
        _action(
            "cast.start",
            "Iniciar transmissão",
            "/cast/start",
            service="bridge",
            screen="cast",
            control="cast-start",
            schema=_schema("receiverId", receiverId="string", profile="string", mode="string"),
        ),
        _action(
            "cast.stop",
            "Parar transmissão",
            "/cast/stop",
            service="bridge",
            screen="cast",
            control="cast-stop",
        ),
        _action(
            "cast.status",
            "Status da transmissão",
            "/cast/status",
            service="bridge",
            screen="cast",
            control="cast-status",
            method="GET",
        ),
        _action(
            "cast.sessions",
            "Sessões ativas",
            "/cast/sessions",
            service="bridge",
            screen="cast",
            control="cast-sessions",
            method="GET",
        ),
        # --- Tema --------------------------------------------------------
        _action(
            "theme.list",
            "Listar temas disponíveis",
            "/theme/list",
            service="system",
            screen="system",
            control="theme-list",
            method="GET",
        ),
        _action(
            "theme.apply",
            "Aplicar tema",
            "/theme/apply",
            service="system",
            screen="system",
            control="theme-apply",
            schema=_schema("themeId", themeId="string"),
        ),
        _action(
            "theme.apply.confirm",
            "Confirmar aplicação de tema",
            "/theme/apply/confirm",
            service="system",
            screen="system",
            control="theme-apply-confirm",
            schema=_schema("planId", planId="string", confirmToken="string"),
            confirmation="token",
        ),
        _action(
            "theme.apply.rollback",
            "Reverter aplicação de tema",
            "/theme/apply/rollback",
            service="system",
            screen="system",
            control="theme-apply-rollback",
            schema=_schema("operationId", operationId="string"),
            rollback_endpoint="/theme/apply/rollback",
        ),
        # --- Editor de temas ----------------------------------------------
        _action(
            "theme.editor.load",
            "Carregar tema para edição",
            "/theme/editor/load",
            service="system",
            screen="system",
            control="theme-editor-load",
            method="GET",
            schema=_schema("themeId", themeId="string"),
        ),
        _action(
            "theme.editor.create",
            "Criar novo tema",
            "/theme/editor/create",
            service="system",
            screen="system",
            control="theme-editor-create",
            schema=_schema("name", name="string"),
        ),
        _action(
            "theme.editor.set-tokens",
            "Alterar tokens de tema",
            "/theme/editor/set-tokens",
            service="system",
            screen="system",
            control="theme-editor-set-tokens",
            schema=_schema("sessionId", sessionId="string", category="string", values="object"),
        ),
        _action(
            "theme.editor.set-metadata",
            "Alterar metadados de tema",
            "/theme/editor/set-metadata",
            service="system",
            screen="system",
            control="theme-editor-set-metadata",
            schema=_schema("sessionId", sessionId="string", field="string"),
        ),
        _action(
            "theme.editor.preview",
            "Preview ao vivo do tema editado",
            "/theme/editor/preview",
            service="system",
            screen="system",
            control="theme-editor-preview",
            schema=_schema("sessionId", sessionId="string"),
        ),
        _action(
            "theme.editor.save",
            "Salvar tema editado",
            "/theme/editor/save",
            service="system",
            screen="system",
            control="theme-editor-save",
            schema=_schema("sessionId", sessionId="string"),
        ),
        _action(
            "theme.editor.export",
            "Exportar tema como ZIP",
            "/theme/editor/export",
            service="system",
            screen="system",
            control="theme-editor-export",
            schema=_schema("sessionId", sessionId="string"),
        ),
        _action(
            "theme.editor.cancel",
            "Cancelar sessão de edição",
            "/theme/editor/cancel",
            service="system",
            screen="system",
            control="theme-editor-cancel",
            schema=_schema("sessionId", sessionId="string"),
        ),
    ]
    return {
        "schemaVersion": 1,
        "states": list(_STATES),
        "actions": actions,
        "byId": {action["id"]: action for action in actions},
    }
